name: Auto deploy nodejs app to cpanel using github actions
on:
  push:
    branches:
      - main
jobs:
  deploy-to-cpanel:
    name: 🎉 Deploy-nodejs-app-to-cpanel
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.GIT_CPANEL_NODE_SERVER }}
          username: ${{ secrets.GIT_CPANEL_NODE_USER }}
          password: ${{ secrets.GIT_CPANEL_NODE_PWD }}
          protocol: ${{ secrets.GIT_CPANEL_NODE_PROTOCOL }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md

      - name: Restart the node express server on done
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GIT_CPANEL_NODE_SSH_HOST }}
          username: ${{ secrets.GIT_CPANEL_NODE_SSH_USER }}
          key: ${{ secrets.GIT_CPANEL_NODE_SSH_KEY }}
          passphrase: ${{ secrets.GIT_CPANEL_NODE_SSH_PASSPHRASE }}
          port: ${{ secrets.GIT_CPANEL_NODE_SSH_PORT }}
          script: |
            ${{ secrets.GIT_CPANEL_NODE_SSH_DIR}}
            npm install
            npm install pm2@latest -g
            pm2 stop app.js
            pm2 start app.js